image: node:latest

stages:
  - merge
  - publish

before_script:
  - git submodule update --init .citools
  - source .ci/setup-env.sh
  - npx -p @nofrills/tasks@^10.0.0 cli-tasks ci:install
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

cache:
  paths:
    - node_modules

continuous:
  stage: publish
  except:
    - tags
  only:
    - /feature\/.*/
    - /fix\/.*/
  script:
    - npx -p @nofrills/tasks cli-tasks ci:publish:canary

prerelease:
  stage: publish
  except:
    - tags
  only:
    - develop
  script:
    - npx -p @nofrills/tasks cli-tasks ci:publish:prerelease

release:
  stage: publish
  except:
    - tags
  only:
    - master
  script:
    - npx -p @nofrills/tasks cli-tasks ci:publish:release
