image: node:latest

stages:
  - publish

before_script:
  - git submodule update --init .citools
  - source .ci-env
  - npx -p @nofrills/tasks cli-tasks ci:install

cache:
  paths:
    - node_modules

continuous:
  stage: publish
  only:
    - /feature\/.*/
    - /fix\/.*/
  script:
    - npx -p @nofrills/tasks cli-tasks ci:publish:canary

prerelease:
  stage: publish
  only:
    - develop
  script:
    - npx -p @nofrills/tasks cli-tasks ci:publish:prerelease

release:
  stage: publish
  only:
    - master
  script:
    - npx -p @nofrills/tasks cli-tasks ci:publish:release
